# Generated by Django 5.1.3 on 2024-12-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_payment_is_successful_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
