# Generated by Django 5.1.3 on 2024-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
