# Generated by Django 5.1.3 on 2024-12-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cartitem_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pizza'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.topping'),
        ),
    ]
